Some edit to emacs config.

diff --git a/scripts/tldr b/scripts/tldr
--- a/scripts/tldr
+++ b/scripts/tldr
@@ -1,12 +1,13 @@
-#!/bin/bash
+#!/usr/bin/env bash
 set +vx -o pipefail
 [[ $- = *i* ]] && echo "Don't source this script!" && return 1
-version='0.3'
-# tldr-bash-client version 0.3
+version='0.40'
+# tldr-bash-client version 0.40
 # Bash client for tldr: community driven man-by-example
-# - forked from Ray Lee, http://github.com/raylee/tldr
-# - modified and expanded by pepa65: http://github.com/pepa65/tldr-bash-client
-# Requiring: coreutils, less, grep, unzip, curl/wget
+# - forked from Ray Lee, https://github.com/raylee/tldr
+# - modified and expanded by pepa65: https://gitlab.com/pepa65/tldr-bash-client
+# - binary download: http://4e4.win/tldr
+# Requiring: coreutils, grep, unzip, curl/wget, less (optional)
 
 # The 5 elements in TLDR markup that can be styled with these colors and
 # backgrounds (last one specified will be used) and modes (more can apply):
@@ -40,29 +41,36 @@ version='0.3'
 # Alternative location of pages cache
 : "${TLDR_CACHE:= }"
 
+# Usage of 'less' or 'cat' for output (set to '0' for cat)
+: "${TLDR_LESS:= }"
+
+## Function definitions
+
 # $1: [optional] exit code; Uses: version cachedir
 Usage(){
 	Out "$(cat <<-EOF
-		$HHE $version
+		 $E$version
 
-		$HDE USAGE: $HHE$(basename "$0")$XHHE [${HOP}option$XHOP] [${HPL}platform$XHPL/]${HCO}command$XHCO
+		 ${HDE}USAGE: $HHE$(basename "$0")$XHHE [${HOP}option$XHOP] [${HPL}platform$XHPL/]${HCO}command$XHCO
 
-		$HDE [${HPL}platform$XHPL/]${HCO}command$XHCO:          Show page for$HCO command$XHCO (from$HPL platform$XHPL)
+		 $HDE[${HPL}platform$XHPL/]${HCO}command$XHCO:          Show page for ${HCO}command$XHCO (from ${HPL}platform$XHPL)
 
-		$HPL platform$XHPL is optionally one of:$HPL common$XHPL,$HPL linux$XHPL,$HPL osx$XHPL,$HPL sunos$XHPL
+		 ${HPL}platform$XHPL (optional) one of: ${HPL}common$XHPL, ${HPL}linux$XHPL, ${HPL}osx$XHPL, ${HPL}sunos$XHPL, ${HPL}windows$XHPL,
+		                             ${HPL}current$XHPL (includes ${HPL}common$XHPL)
 
-		$HOP option$XHOP is optionally one of:
-		  $HOP-l$XHOP,$HOP --list$XHOP [${HPL}platform$XHPL]:      Show all available pages (from$HPL platform$XHPL)
-		  $HOP-r$XHOP,$HOP --render$XHOP ${HFI}file$XHFI:          Render a local$HFI file$XHFI as tldr markdown
-		  $HOP-m$XHOP,$HOP --markdown$XHOP ${HCO}command$XHCO:     Show the markdown source for$HCO command$XHCO
-		  $HOP-c$XHOP,$HOP --cache$XHOP:                Cache all pages by downloading archive from repo
-		  $HOP-u$XHOP,$HOP --update$XHOP:               Re-download index file from repo
-		  $HOP-v$XHOP,$HOP --version$XHOP:              Version number and repo location
-		  $HDE[$HOP-h$XHOP,$HOP -?$XHOP,$HOP --help$XHOP]:           This help overview
+		 ${HOP}option$XHOP is optionally one of:
+		  $HOP-s$XHOP, $HOP--search$XHOP ${HFI}regex$XHFI:         Search for ${HFI}regex$XHFI in all tldr pages
+		  $HOP-l$XHOP, $HOP--list$XHOP [${HPL}platform$XHPL]:      List all pages (from ${HPL}platform$XHPL)
+		  $HOP-a$XHOP, $HOP--list-all$XHOP:             List all pages from current platform + common
+		  $HOP-r$XHOP, $HOP--render$XHOP ${HFI}file$XHFI:          Render ${HFI}file$XHFI as tldr markdown
+		  $HOP-m$XHOP, $HOP--markdown$XHOP ${HCO}command$XHCO:     Show the markdown source for ${HCO}command$XHCO
+		  $HOP-u$XHOP, $HOP--update$XHOP:               Update the pages cache by downloading repo archive
+		  $HOP-v$XHOP, $HOP--version$XHOP:              Version number and gitlab repo location
+		  $HDE[$HOP-h$XHOP, $HOP-?$XHOP, $HOP--help$XHOP]:           This help overview
 
-		$HDE Element styling:$XHDE$T Title$XT$D Description$XD$E Example$XD$C Code$XC$V Value$XV
-		$HDE All pages and the index are cached locally under $HUR$cachedir$XHUR.
-		$HDE By default, the cached copies will be freshly downloaded after $HUR${TLDR_EXPIRY// /}$XHUR days.
+		 ${HDE}Element styling:$XHDE ${T}Title$XT ${D}Description$XD ${E}Example$XE ${C}Code$XC ${V}Value$XV
+		 ${HDE}All pages and the index are cached locally under $HUR$cachedir$XHUR.
+		 ${HDE}By default, the cached copies will be freshly downloaded after $HUR${TLDR_EXPIRY// /}$XHUR days.
 		EOF
 	)"
 	exit "${1:-0}"
@@ -90,7 +98,7 @@ Style(){
 		STYLES+=${color[$style]:-}${bg[$style]:-}${mode[$style]:-}
 		XSTYLES=${xmode[$style]:-}${xbg[$style]:-}${xcolor[$style]:-}$XSTYLES
 	done
-}	
+}
 
 # Sets: color xcolor bg xbg mode xmode
 Init_term(){
@@ -173,72 +181,69 @@ Init_term(){
 # $1: page
 Recent(){ find "$1" -mtime -"${TLDR_EXPIRY// /}" >/dev/null 2>&1;}
 
-# Download index.json; Uses: index index_url base_url zip_url dl
-Update_index(){
-	$dl "$index" "$index_url" && Inf "Index file $I$index$XI freshly downloaded" || {
-		Err "Could not download index from $I$index_url$XI"
-		exit 2
-	}
-}
-
 # Initialize globals, check the environment; Uses: config cachedir version
 # Sets: stdout os version dl
 Config(){
+	type -p less >/dev/null || TLDR_LESS=0
+
 	os=common stdout='' Q='"' N=$'\n'
 	case "$(uname -s)" in
 		Darwin) os='osx' ;;
 		Linux) os='linux' ;;
 		SunOS) os='sunos' ;;
+		CYGWIN*) os='windows' ;;
+		MINGW*) os='windows' ;;
 	esac
 	Init_term
-	trap 'less -~RXQFP"Browse up/down, press Q to exit " <<<"$stdout"' EXIT
+	[[ $TLDR_LESS = 0 ]] && 
+		trap 'cat <<<"$stdout"' EXIT ||
+		trap 'less -~RXQFP"Browse up/down, press Q to exit " <<<"$stdout"' EXIT
 
-	version="tldr-bash-client version $version $XB$URL http://github.com/pepa65/tldr-bash-client$XURL"
+	version="tldr-bash-client version $version$XB ${URL}http://gitlab.com/pepa65/tldr-bash-client$XURL"
 
 	# Select download method
-	dl="$(type -p curl) -sfo" || {
-		dl="$(type -p wget) -qNO" || {
-			Err "tldr requires$I curl$XI or$I wget $XI installed in your path"
+	dl="$(type -p curl) -sLfo" || {
+		dl="$(type -p wget) --max-redirect=20 -qNO" || {
+			Err "tldr requires ${I}curl$XI or ${I}wget$XI installed in your path"
 			exit 3
 		}
 	}
 
-	base_url='https://raw.githubusercontent.com/tldr-pages/tldr/master/pages'
-	zip_url='http://tldr-pages.github.io/assets/tldr.zip'
-	index_url='http://tldr-pages.github.io/assets/index.json'
+	pages_url='https://raw.githubusercontent.com/tldr-pages/tldr/master/pages'
+	zip_url='http://tldr.sh/assets/tldr.zip'
 
-	read cachedir <<<$TLDR_CACHE
-	[[ $cachedir ]] || {
-		[[ $XDG_DATA_HOME ]] && cachedir=$XDG_DATA_HOME/tldr \
-				|| cachedir=$HOME/.local/share/tldr
-	}
+	cachedir=$(echo $TLDR_CACHE)
+	if [[ -z $cachedir ]]
+	then
+		[[ $XDG_DATA_HOME ]] && cachedir=$XDG_DATA_HOME/tldr ||
+			cachedir=$HOME/.local/share/tldr
+	fi
 	[[ -d "$cachedir" ]] || mkdir -p "$cachedir" || {
 		Err "Can't create the pages cache location $cachedir"
 		exit 4
 	}
 	index=$cachedir/index.json
 	# update if the file doesn't exists, or if it's older than $TLDR_EXPIRY
-	[[ -f $index ]] && Recent "$index" || Update_index
+	[[ -f $index ]] && Recent "$index" || Cache_fill
 }
 
-# $1: error message; Uses: md line ln
+# $1: error message; Uses: md REPLY ln
 Unlinted(){
-	Err "Page $I$md$XI not properly linted!$N${ERRSP}${ERR}Line $I$ln$XI [$XERR$U$line$XU$ERR]$N$ERRSP$ERR$1"
-	exit 4
+	Err "Page $I$md$XI not properly linted!$N${ERRSP}${ERR}Line $I$ln$XI [$XERR$U$REPLY$XU$ERR]$N$ERRSP$ERR$1"
+	exit 5
 }
 
-# $1: page; Uses: index index_url cachedir base_url platform os dl cached md
+# $1: page; Uses: index cachedir pages_url platform os dl cached md
 # Sets: cached md
 Get_tldr(){
-	local desc err notfound
+	local desc err=0 notfound
 	# convert the local platform name to tldr's version
 	# extract the platform key from index.json, return preferred subpath to page
-	desc=$(tr '{' '\n' <$index |grep "\"name\":\"$1\"")
+	desc=$(tr '{' '\n' <"$index" |grep "\"name\":\"$1\"")
 	# results in, eg, "name":"netstat","platform":["linux","osx"]},
 
-	[[ $desc ]] || return  # just not found
+	[[ $desc ]] || return  # nothing found
 
-	err=0
 	if [[ $platform ]]
 	then  # platform given on commandline
 		[[ ! $desc =~ \"$platform\" ]] && notfound=$I$platform$XI && err=1 || md=$platform/$1.md
@@ -249,7 +254,7 @@ Get_tldr(){
 		}
 	fi
 	# if no page found yet, try the system platform
-	[[ $md ]] || [[ $platform = "$os" ]] || {
+	[[ $md ]] || [[ $platform = $os ]] || {
 			[[ $desc =~ \"$os\" ]] && md=$os/$1.md
 	} || {
 		notfound+=" or $I$os$XI"
@@ -263,157 +268,187 @@ Get_tldr(){
 	cached=$cachedir/$md
 	Recent "$cached" || {
 		mkdir -p "${cached%/*}"
-		$dl "$cached" "$base_url/$md" || Err "Could not download page $I$cached$XI from index $U$index_url$XU"
+		$dl "$cached" "$pages_url/$md" || Err "Could not download page $I$cached$XI with $dl"
 	}
 }
 
-# $1: text; Uses: page stdout; Sets: ln line
+# $1: file (optional); Uses: page stdout; Sets: ln REPLY
 Display_tldr(){
 	local newfmt len val
-	ln=0 line=''
+	ln=0 REPLY=''
 	[[ $md ]] || md=$1
 	# Read full lines, and process even when no newline at the end
-	while read -r line || [[ $line ]]
+	while read -r || [[ $REPLY ]]
 	do
 		((++ln))
 		((ln==1)) && {
-			[[ ${line:0:1} = '#' ]] && newfmt=0 || newfmt=1
+			[[ ${REPLY:0:1} = '#' ]] && newfmt=0 || newfmt=1
 			((newfmt)) && {
-				[[ $line ]] || Unlinted "No title"
-				Out "$TNL$TSP$T$line$XT"
-				len=${#line}
-				read -r; ((++ln))
-				[[ $line =~ [^=] ]] && Unlinted "Title underline must be equal signs"
-				((len!=${#line})) && Unlinted "Underline length not equal to title's"
-				read -r; ((++ln))
+				[[ $REPLY ]] || Unlinted "Empty title"
+				Out "$TNL$TSP$T$REPLY$XT"
+				len=${#REPLY}  # title length
+				read -r
+				((++ln))
+				[[ $REPLY =~ [^=] ]] && Unlinted "Title underline must be equal signs"
+				((len!=${#REPLY})) && Unlinted "Underline length not equal to title's"
+				read -r
+				((++ln))
 			}
 		}
-		case "${line:0:1}" in  # first character
+		case "${REPLY:0:1}" in  # first character
 			'#') ((newfmt)) && Unlinted "Bad first character"
-				((${#line} <= 2)) && Unlinted "No title"
-				[[ ! ${line:1:1} = ' ' ]] && Unlinted "2nd character no space"
-				Out "$TNL$TSP$T${line:2}$XT" ;;
-			'>') ((${#line} <= 3)) && Unlinted "No valid desciption"
-				[[ ! ${line:1:1} = ' ' ]] && Unlinted "2nd character no space"
-				[[ ! ${line: -1} = '.' ]] && Unlinted "Description doesn't end in full stop"
-				Out "$DNL$DSP$D${line:2}$XD"
+				((${#REPLY} <= 2)) && Unlinted "No title"
+				[[ ! ${REPLY:1:1} = ' ' ]] && Unlinted "2nd character no space"
+				Out "$TNL$TSP$T${REPLY:2}$XT" ;;
+			'>') ((${#REPLY} <= 3)) && Unlinted "No valid desciption"
+				[[ ! ${REPLY:1:1} = ' ' ]] && Unlinted "2nd character no space"
+				[[ ! ${REPLY: -1} = '.' ]] && Unlinted "Description doesn't end in full stop"
+				Out "$DNL$DSP$D${REPLY:2}$XD"
 				DNL='' ;;
 			'-') ((newfmt)) && Unlinted "Bad first character"
-				((${#line} <= 2)) && Unlinted "No example content"
-				[[ ! ${line:1:1} = ' ' ]] && Unlinted "2nd character no space"
-				Out "$ENL$ESP$E${line:2}$XE" ;;
+				((${#REPLY} <= 2)) && Unlinted "No example content"
+				[[ ! ${REPLY:1:1} = ' ' ]] && Unlinted "2nd character no space"
+				Out "$ENL$ESP$E${REPLY:2}$XE" ;;
 			' ') ((newfmt)) || Unlinted "Bad first character"
-				((${#line} <= 4)) && Unlinted "No valid code content"
-				[[ ${line:0:4} = '    ' ]] || Unlinted "No four spaces before code"
-				val=${line:4}
+				((${#REPLY} <= 4)) && Unlinted "No valid code content"
+				[[ ${REPLY:0:4} = '    ' ]] || Unlinted "No four spaces before code"
+				val=${REPLY:4}
 				# Value: convert {{value}}
 				val=${val//\{\{/$CX$V}
 				val=${val//\}\}/$XV$C}
 				Out "$CNL$CSP$C$val$XC" ;;
 			'`') ((newfmt)) && Unlinted "Bad first character"
-				((${#line} <= 2)) && Unlinted "No valid code content"
-				[[ ! ${line: -1} = '`' ]] && Unlinted "Code doesn't end in backtick"
-				val=${line:1:-1}
+				((${#REPLY} <= 2)) && Unlinted "No valid code content"
+				[[ ! ${REPLY: -1} = '`' ]] && Unlinted "Code doesn't end in backtick"
+				val=${REPLY:1:${#REPLY}-2}
 				# Value: convert {{value}}
 				val=${val//\{\{/$CX$V}
 				val=${val//\}\}/$XV$C}
 				Out "$CNL$CSP$C$val$XC" ;;
 			'') continue ;;
 			*) ((newfmt)) || Unlinted "Bad first character"
-				[[ -z $line ]] && Unlinted "No example content"
-				Out "$ENL$EPS$E$line$XE" ;;
+				[[ -z $REPLY ]] && Unlinted "No example content"
+				Out "$ENL$ESP$E$REPLY$XE" ;;
 		esac
 	done <"$1"
-	trap 'less +Gg -~RXQFP"%pB\% tldr $I$page$XI - browse up/down, press Q to exit" <<<"$stdout"' EXIT
+	[[ $TLDR_LESS = 0 ]] && 
+		trap 'cat <<<"$stdout"' EXIT ||
+		trap 'less +Gg -~RXQFP"%pB\% tldr $I$page$XI - browse up/down, press Q to exit" <<<"$stdout"' EXIT
 }
 
 # $1: exit code; Uses: platform index
 List_pages(){
 	local platformtext c1 c2 c3
-	[[ $platform ]] && platformtext=" from platform $I$platform$XI"
-	Inf "Known tldr pages$platformtext:"
+	[[ $platform ]] && platformtext="platform $I$platform$XI" ||
+		platform=^ platformtext="${I}all$XI platforms"
+	[[ $platform = current ]] && platform="-e $os -e common" &&
+		platformtext="$I$os$XI platform and ${I}common$XI"
+	Inf "Known tldr pages from $platformtext:"
 	Out "$(while read -r c1 c2 c3; do printf "%-19s %-19s %-19s %-19s$N" $c1 $c2 $c3; done \
-			<<<$(tr '{' '\n' <$index |grep "$platform" |cut -d "$Q" -f4))"
+			<<<$(tr '{' '\n' <"$index" |grep $platform |cut -d "$Q" -f4))"
 	exit "$1"
+}
+
+# $1: regex, $2: exit code; Uses: cachedir
+Find_regex(){
+	local list=$(grep "$1" "$cachedir"/*/*.md |cut -d: -f1) regex="$U$1$XU"
+	local n=$(wc -l <<<"$list")
+	list=$(sort -u <<<"$list")
+	[[ -z $list ]] && Err "Regex $regex not found" && exit 6
+	local t=$(wc -l <<<"$list")
+	if ((t==1))
+	then
+		Display_tldr "$list"
+	else
+		Inf "Regex $regex $I$n$XI times found in these $I$t$XI tldr pages:"
+		Out "$(while read -r c1 c2 c3; do printf "%-19s %-19s %-19s %-19s$N" $c1 $c2 $c3; done \
+			<<<$(sed -e 's@.*/@@' -e 's@...$@@' <<<"$list"))"
+	fi
+	exit "$2"
 }
 
 # $1: exit code; Uses: dl cachedir zip_url
 Cache_fill(){
+	updated=0
 	local tmp unzip
+	unzip="$(type -p unzip) -q" || {
+		Err "tldr requires ${I}unzip$XI to fill the cache"
+		exit 7
+	}
 	tmp=$(mktemp -d)
 	$dl "$tmp/pages.zip" "$zip_url" || {
 		rm -- "$tmp"
-		Err "Could not download pages archive from $U$zip_url$XU"
-		exit 6
+		Err "Could not download pages archive from $U$zip_url$XU with $dl"
+		exit 8
 	}
-	unzip="$(type -p unzip) -q" || {
+	$unzip "$tmp/pages.zip" -d "$tmp" 'pages/**' || {
 		rm -- "$tmp"
-		Err "Unzip is necessary to fill the cache"
-		exit 7
+		Err "Couldn't unzip the cache archive on $tmp/pages.zip"
+		exit 9
 	}
-	$unzip "$tmp/pages.zip" -d "$tmp" 'pages/*'
 	rm -rf -- "${cachedir:?}/"*
 	mv -- "$tmp/pages/"* "${cachedir:?}/"
 	rm -rf -- "$tmp"
 	Inf "Pages cached in $U$cachedir$XU"
-	exit "$1"
+	updated=1
 }
 
 # $@: commandline parameters; Uses: version cached; Sets: platform page
 Main(){
-	local markdown err
+	local markdown=0 err=0 nomore='No more command line arguments allowed'
 	Config
-	markdown=0 err=0
 	case "$1" in
+	-s|--search) [[ -z $2 ]] && Err "Search term (regex) needed" && Usage 10
+		[[ $3 ]] && Err "$nomore" && err=11
+		Find_regex "$2" "$err" ;;
 	-l|--list) [[ $2 ]] && {
 			platform=$2
-			[[ ,common,linux,osx,sunos, = *,$platform,* ]] || {
-				Err "Unknown platform $I$platform$XI"
-				Usage 8
-			}
-			[[ $3 ]] && Err "No more command line arguments allowed" && err=9
+			[[ ,common,linux,osx,sunos,windows,current, != *,$platform,* ]] &&
+				Err "Unknown platform $I$platform$XI" && Usage 12
+			[[ $3 ]] && Err "$nomore" && err=13
 		}
 		List_pages "$err" ;;
-	-c|--cache) [[ $2 ]] && Err "No more command line arguments allowed" && err=10
-		Cache_fill "$err" ;;
-	-v|--version) [[ $2 ]] && Err "No more command line arguments allowed" && err=11
+	-a|--list-all) [[ $2 ]] && Err "$nomore" && err=14
+		platform=current
+		List_pages $err ;;
+	-u|--update) [[ $2 ]] && Err "$nomore" && err=15
+		((updated)) || Cache_fill
+		exit "$err" ;;
+	-v|--version) [[ $2 ]] && Err "$nomore" && err=16
 		Inf "$version"
 		exit "$err" ;;
-	-u|--update) [[ $2 ]] && Err "No more command line arguments allowed" && err=12
-		Update_index
-		exit "$err" ;;
-	-r|--render) [[ -z $2 ]] && Err "Specify a file to render" && Usage 13
-		[[ $3 ]] && Err "No more command line arguments allowed" && err=14
+	-r|--render) [[ -z $2 ]] && Err "Specify a file to render" && Usage 17
+		[[ $3 ]] && Err "$nomore" && err=18
 		[[ -f "$2" ]] && {
 			Display_tldr "$2" && exit "$err"
 			Err "A file error occured"
-			exit 15
-		} || Err "No file:$I $2$XI" && exit 16 ;;
+			exit 19
+		} || Err "No file: ${I}$2$XI" && exit 20 ;;
 	-m|--markdown) shift
 		page=$*
-		[[ -z $page ]] && Err "Specify a page to display" && Usage 17
+		[[ -z $page ]] && Err "Specify a page to display" && Usage 21
 		[[ -f "$page" && ${page: -3:3} = .md ]] && Out "$(cat "$page")" && exit 0
 		markdown=1 ;;
-	''|-h|-\?|--help) [[ $2 ]] && Err "No more command line arguments allowed" && err=18
+	''|-h|-\?|--help) [[ $2 ]] && Err "$nomore" && err=22
 		Usage "$err" ;;
-	-*) Err "Unrecognized option $I$1$XI"; Usage 19 ;;
+	-*) Err "Unrecognized option $I$1$XI"; Usage 23 ;;
 	*) page=$* ;;
 	esac
 
-	[[ -z $page ]] && Err "No command specified" && Usage 20
-	[[ $page =~ ' -' || ${page:0:1} = '-' ]] && Err "Only one option allowed" && Usage 21
+	[[ -z $page ]] && Err "No command specified" && Usage 24
+	[[ ${page:0:1} = '-' || $page = *' '-* ]] && Err "Only one option allowed" && Usage 25
 	[[ $page = */* ]] && platform=${page%/*} && page=${page##*/}
-	[[ $platform && ,common,linux,osx,sunos, != *,$platform,* ]] && {
+	[[ $platform && ,common,linux,osx,sunos,windows, != *,$platform,* ]] && {
 		Err "Unknown platform $I$platform$XI"
-		Usage 22
+		Usage 26
 	}
 
 	Get_tldr "${page// /-}"
 	[[ ! -s $cached ]] && Err "tldr page for command $I$page$XI not found" \
-			&& Inf "Contribute new pages at:$XB$URL https://github.com/tldr-pages/tldr$XURL" && exit 23
+			&& Inf "Contribute new pages at:$XB ${URL}https://github.com/tldr-pages/tldr$XURL" && exit 27
 	((markdown)) && Out "$(cat "$cached")" || Display_tldr "$cached"
 }
 
 Main "$@"
-# The error trap will output the accumulated stdout
+# The exit trap will output the accumulated stdout
 exit 0
